### ISSUE TITLE
ReadMe 

### ISSUE THREAD

**Issue by Samlewis99** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group1#6]
Hey Everyone, I'm going to start pulling together our readme. If you could let me know what your map_maker notebooks are mapping I can format some sections for us to all put our own information in

**Comment by Samlewis99** [comment]
I have created a new branch "readme" for us to commit changes to this file

**Comment by g-nym** [comment]
Hey @Samlewis99 would you prefer us to submit our summaries to you, and then you can update the Readme document? Should we comment them here?

**Comment by XuluLin** [comment]
I think it would be better if we just work on our own summaries first then merge it together. Also I looked at what @Samlewis99 has written so far. Are we going to re-organise my_functions.py into different modules like seismic mapping, coastline feature mapping etc.?

**Comment by Samlewis99** [comment]
Hmm yes if we are all working on separate copies it may get very messy when we try to merge them together. I think we can either just commit our changes to the main regularly so it up to date and wont get as messy. Or as you said I am happy if you want to send me your edits and i can merge them.
Let me know what's easiest.

**Comment by g-nym** [comment]
I *think* I added my changes to the main branch when I was in the process of resolving other conflicts. It looks like it only needs a small blurb for each of us, and the bulk of it is already solid -- thanks again for whipping that up Sam.

Here's my text blurb:
Harmful Algae Blooms v. Biodiversity

Two data types have been preloaded and formatted: a point data analysis of harmful algae blooms and raster data of biodiversity functional types provided by CA.gov and Earth Data.

**Comment by XuluLin** [comment]
# About this repository 

This repository is written by Sam, Gwendolyn and Xulu for assignment 1 EMSC-4033/8033, semester 1, 2022. This is a repository for mapping a region of interest in Python. 


# Project aims  

This project consists of three aims. 

- Mapping geographical features including coastlines, lakes, rivers, and ocean. This is achieved using Cartopy NaturalEarthFeature (https://scitools.org.uk/cartopy/docs/v0.14/matplotlib/feature_interface.html) with classic Python Matplotlib, given requested resolution and region coordinates. Cartopy is a popular mapping tool in the geoscience community due to its simplicity and quality visualisation of scientific data. 


- Mapping point data. This repository provides two data options: seismicity and Harmful Algae Blooms v. Biodiversity. The seimic events are downloaded from IRIS FDSN server (http://www.fdsn.org/datacenters/detail/IRISDMC/) We use Obspy library in Python (https://docs.obspy.org/) to query, retrieve and process seismic data. 

*Harmful algae needs Gwen to fill in.*


- Mapping raster data. This repository provides the option of mapping seafloor age data and visualising it as contour lines for the region of interest. The data is available at https://www.earthbyte.org/category/resources/data-models/seafloor-age/. 

*Harmful algae needs Gwen to fill in.*



# How do we use it

The plotting Jupyter Notebook is 'MapMaker.ipynb'. 



It imports all necessary libraries and functions from the src folder. 



The imported exisiting Python libraries are in 'dependecies.py'. The functions are in the plotting module 'my_function.py'. The testing functions are in the testing module 'test_functions.py' and you can run tests in 'RunTests.ipynb' to help you debug when running this source scripts. 



The plotting module of this repository is 'my_functions.py'. It contains:


- Geographical feature mapping functions: my_coastlines, my_water_features, my_basemaps. 

- Seismic event mapping functions: download_point_data, my_point_data.  

*Harmful algae needs Gwen to fill in.*

- Raster data mapping functions: download raster_data, my_global_raster_data. 


***This is my draft for the README.md file. I have actually written out the whole thing just so that @Samlewis99 can comapre this with what he already got and we could add bits and pieces missing. I kind of written it in a slightly different structure. But again it is adjustable.

**Comment by g-nym** [comment]
This formatting implies that all the data is available in each notebook., but my data is only available if you run my folder. I've adjusted this text to reflect that.

Overall, this formatting might be preferable. I believe Sam set up the other Readme under the assumption that each of us would use different data sources. I went ahead and edited it for flow and some content cleanup

> # About this repository
> 
> This repository is written by Sam, Gwendolyn and Xulu for assignment 1 EMSC-4033/8033, semester 1, 2022.  Within this repository are three folders containing a MapMaker program and its supporting files.
> # Project aims
> 
> This project aims to combine three types of geological data into one useful map.
> 
>     * Mapping geographical features including coastlines, lakes, rivers, and ocean. This is achieved using Cartopy NaturalEarthFeature (https://scitools.org.uk/cartopy/docs/v0.14/matplotlib/feature_interface.html) with classic Python Matplotlib, given requested resolution and region coordinates. Cartopy is a popular mapping tool in the geoscience community due to its simplicity and quality visualisation of scientific data.
> 
>     * Mapping point data. This repository provieds point data for  seimic events downloaded from IRIS FDSN server (http://www.fdsn.org/datacenters/detail/IRISDMC/) We use Obspy library in Python (https://docs.obspy.org/) to query, retrieve and process seismic data.
> 
>     * Mapping raster data. This repository provides the option of mapping seafloor age data and visualising it as contour lines for the region of interest. The data is available at https://www.earthbyte.org/category/resources/data-models/seafloor-age/.
> 
> [See Note about Alternate Data below]
> 
> # How to Use
> 
> The plotting program 'MapMaker.ipynb' is a Jupyter Notebook ready-to-run with all the necessary support files arranged in each folder: 'Sam', 'Xulu', and 'Gwen'.
> 
> It imports all necessary libraries and functions from the src folder, which include:
> 
>  * 'dependencies.py'  -- The requisite Python libraries and modules are called within 'dependecies.py'. 
>
> * 'my_functions.py' -- Which contains: Geographical feature mapping functions: my_coastlines, my_water_features, my_basemaps; Seismic event mapping functions: download_point_data, my_point_data; Seafloor Age mapping functions: download raster_data, my_global_raster_data.
>
>
>   ''RunTests.ipynb' is another notebook alongside the MapMaker which provides robust tests that are defined within 'test_functions.py' designed for useful debugging. Note: tests vary in each folder ('Sam', 'Xulu', and 'Gwen')
>
>
> 
> 
># Alternative Data
> The Sam and Xulu folders contain the seismic and seafloor data defined above. The folder 'Gwen' contains alternate data that documents Freshwater Harmful Algae Blooms in California and Functional Biodiversity in the contiguous USA.

**Comment by XuluLin** [comment]
# Group Report

*From instructors:* Please document here how you made the repository including:

- pull requests
- pull request reviews
- collaborative editing of documents
- creating and resolving issues
- adding tests
- adding documentation/docstrings


## Overview of the repository 

EMSC-4033-2022-assignment-Group1 is created by Sam, Gwendolyn and Xulu. This is the repository where we collaborated to produce relevant functions and modules to map a region of interest using 
Cartopy package in Python. More details about the functionality of this repository can be referred to README.md. 


## Pull requests and pull request reviews 

We worked individually to produce our own version of MapMaker.ipynb, RunTests.ipynb, test_functions.py and my_functions.py. We committed our changes in our own branch and pushed it to the main
as pull requests. 
Individual work was accomplished in Jupyter Hub, as per course structure, and initial pushes originated from the Jupyter Hub terminal.
Collaborative work was then communicated through pull requests where we reviewed each other's Jupyter Notebooks and Python modules. 
We commented on places for suggested improvements (e.g. fixing bugs, adding extra comments/docstrings for clarity etc.) to the owner of that version. 
The owner would evaluate the comments and made relevant changes. Then the pull requests were merged to the main branch to produce the final version. 


## Creating and resolving issues. 

'Issues' is our chat platform. 
We used it to discuss coding questions, confusion on the assessment, general updates on what each other were/should be working on. We assigned each issue to relevant collaborators so that they will be notified.
For individual folders, comments were created both in-line within the documents and as general commentary in the pull request.
Subsequent pull requests and edits were addressed in a combination of the GitHub platform and the Jupyter Hub. Once files (such as the README.md and report.md) were pushed to the GitHub directory, further edits and comments were accomplished in GitHub.
Any final merges with the main directory required approval of at least one other team member, which ensured consistency and mitigated chance of error.


## Collaborative editing of documents

We each again worked individually first to create our own version of documentaion including the README.md and the report.md file. We committed the changes we made as pull requests for others to, predominantly within the GitHub interface. After we combined everyone's opinions, we merged them together and pushed it to the main branch.    


## Adding tests

Since we each worked separately first, we all had different ways or considerations for testing. We reviewed each others' test module in pull requests. 
We discarded redundant test functions and merged them together as our final test module.

**Comment by g-nym** [comment]
Drafts for both the readme and report have been updated and merged to main branch. Closing issue.
